apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  ES_PASSWORD: {{ .Values.secrets.esPassword | quote }}
  WSO2_ADMIN_PASSWORD: {{ .Values.secrets.wso2AdminPassword | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  GROK_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ADMIN_DEFAULT_PASSWORD: {{ .Values.secrets.adminDefaultPassword | quote }}
