gcp:
  enabled: false

wso2:
  apim:
    version: "4.6.0"
    configurations:
      adminUsername: "admin"
      adminPassword: "admin123"
      encryption:
        key: "da5a4cf0765600a9ba2be3ad8c393c2ab155cf0028b2f46524883246725a9ed3"
      databases:
        type: "h2"
        jdbc:
          driver: "org.h2.Driver"
        apim_db:
          url: "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
          username: "wso2carbon"
          password: "wso2carbon"
        shared_db:
          url: "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
          username: "wso2carbon"
          password: "wso2carbon"
      security:
        keystores:
          tls:
            enabled: true
            password: "wso2carbon"
            keyPassword: "wso2carbon"
        truststore:
          password: "wso2carbon"

    tomlConfig: |
      [[apim.key_manager]]
      name = "Resident Key Manager"
      type = "Resident"
      description = "Resident Key Manager using internal K8s cluster DNS"
      enabled = true
      service_url = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/services/"
      token_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/token"
      revoke_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/revoke"
      userinfo_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/userinfo"
      authorize_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/authorize"
      jwks_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/jwks"
      well_known_endpoint = "https://api-gateway-wso2am-all-in-one-am-service.api-gateway.svc.cluster.local:9443/oauth2/token/.well-known/openid-configuration"

  deployment:
    # --- Persistence Enabled ---
    persistentRuntimeArtifacts:
      enabled: true
      storageClass: "standard-rwo"
      size: 10Gi
    image:
      registry: "docker.io"
      repository: "wso2/wso2am"
      tag: "4.6.0"
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        enabled: false
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"
      jvm:
        memory:
          xms: "2048m"
          xmx: "2048m"
    startupProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      failureThreshold: 20
    livenessProbe:
      initialDelaySeconds: 180
      periodSeconds: 15
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 180
      periodSeconds: 15
      failureThreshold: 5

kubernetes:
  gatewayAPI:
    enabled: true
    gatewayName: "wso2am-gateway"
    management:
      enabled: true
      hostname: "am.wso2.com"
    gateway:
      enabled: true
      hostname: "gw.wso2.com"
    websocket:
      enabled: false
    websub:
      enabled: false
