apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/amirchaaari/k8s-manifests.git
    targetRevision: HEAD
    path: releases/data/postgresql
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
