apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: logstash
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/releases/observability/logstash/values.yaml
    - repoURL: https://github.com/amirchaaari/k8s-manifests.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
